version: 2

models:
  - name: fct_bnl__product_customer_month
    columns:
      - name: as_of_month
        tests:
          - not_null
      - name: bu
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: analysis_customer_id
        tests:
          - not_null
      - name: bnl_bucket
        tests:
          - not_null
          - accepted_values:
              values: ['Base', 'New', 'Lost']