version: 2

models:
  - name: int_customer_segmentation__bucket_final
    columns:
      - name: customer_segmentation_bucket_final
        tests:
          - not_null
          - accepted_values:
              values: ['Growing','Declining','Inactive', 'New','Stable']
      - name: override_applied_flag
        tests:
          - not_null