version: 2

models:
  - name: int_bnl__bucket_final
    columns:
      - name: bnl_bucket_final
        tests:
          - not_null
          - accepted_values:
              values: ['Base','New','Lost']
      - name: override_applied_flag
        tests:
          - not_null